[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-timers = "0.3.0"
leptos = { version = "0.7.0", features = ["csr"] }
leptos-use = "0.14.0"
